Repository micro/go-micro, pull requests merged in 2019-08, with the labels that each got.

#668 [WIP] Tunnel loopback connections
  tunnel/default.go
  tunnel/tunnel_test.go
Labels: WIP, enhancement

#672 Monitor outbound links and delete them when disconnected
  tunnel/default.go
  tunnel/tunnel_test.go
Labels: enhancement

#685 Default network implementation
  network/default.go
  network/link/link.go
  network/network.go
  network/options.go
  network/resolver/dns/dns.go
  network/resolver/http/http.go
  network/resolver/registry/registry.go
  network/resolver/resolver.go
  router/router.go
Labels: WIP, enhancement

#706 Broadcast neighbourhood
  network/default.go
  network/network.go
  network/proto/network.micro.go
  network/proto/network.pb.go
  network/proto/network.proto
Labels: enhancement

#708 Set the route.Metric before updating routing table
  network/default.go
Labels: enhancement

#709 Tunnel Direction Fix
  tunnel/default.go
  tunnel/link.go
  tunnel/listener.go
  tunnel/socket.go
Labels: enhancement

#712 Only emit table event if table.Update actually happens
  router/table.go
Labels: bug, enhancement

#713 Avoid setting routes that route back to the node without its being direct GW to dest
  network/default.go
Labels: enhancement

#715 Add proto definitions for network introspection.
  network/proto/network.micro.go
  network/proto/network.pb.go
  network/proto/network.proto
Labels: enhancement
