Repository micro/go-micro, pull requests merged in 2019-10, with the labels that each got.

#810 First commit to add etcd registry support
  config/cmd/cmd.go
  go.mod
  go.sum
  registry/etcd/etcd.go
  registry/etcd/options.go
  registry/etcd/watcher.go
Labels: Registry

#835 Router strategy
  router/default.go
  router/options.go
  router/router.go
Labels: Network

#856 Cloudflare Store implementation for workers KV
  go.mod
  go.sum
  store/cloudflare/cloudflare.go
  store/cloudflare/cloudflare_test.go
Labels: WIP

#861 Distributed storage for certmagic
  .travis.yml
  api/server/acme/acme.go
  api/server/acme/certmagic/certmagic.go
  api/server/acme/certmagic/certmagic_test.go
  api/server/acme/certmagic/storage.go
  api/server/acme/options.go
Labels: WIP
