Repository micro/go-micro, pull requests merged in 2019-11, with the labels that each got.

#906 improve the log of panic recovering
  server/grpc/grpc.go
Labels: enhancement

#904 preallocating slices
  network/service/handler/handler.go
  proxy/mucp/mucp.go
  registry/service/service.go
  store/cloudflare/cloudflare.go
  store/etcd/etcd.go
  tunnel/default.go
Labels: enhancement, perf

#914 Change flap detection configuration
  router/default.go
Labels: Network, enhancement

#915 Flap detection vol2
  router/default.go
  router/default_test.go
  router/table_test.go
Labels: Network, enhancement

#921 K8s list deployments
  runtime/kubernetes/client/api/request.go
  runtime/kubernetes/client/client.go
  runtime/kubernetes/client/kubernetes.go
  runtime/kubernetes/kubernetes.go
Labels: WIP, enhancement

#947 [WIP] Micro Runtime
  go.mod
  go.sum
  runtime/default.go
  runtime/kubernetes/client/api/api_test.go
  runtime/kubernetes/client/api/request.go
  runtime/kubernetes/client/api/response.go
  runtime/kubernetes/client/client.go
  runtime/kubernetes/client/kubernetes.go
  runtime/kubernetes/client/templates.go
  runtime/kubernetes/client/types.go
  runtime/kubernetes/client/utils.go
  runtime/kubernetes/client/utils_test.go
  runtime/kubernetes/client/watch/body.go
  runtime/kubernetes/client/watch/watch.go
  runtime/kubernetes/client/watch/watch_test.go
  runtime/kubernetes/kubernetes.go
  runtime/kubernetes/service.go
  runtime/options.go
  runtime/runtime.go
  runtime/service/handler/handler.go
  runtime/service/proto/runtime.micro.go
  runtime/service/proto/runtime.pb.go
  runtime/service/proto/runtime.proto
Labels: enhancement

#948 Signal handling try #2: through the context
  options.go
  service.go
Labels: enhancement

#964 Fix the router test; get rid of time dependency
  router/default_test.go
Labels: Network, enhancement

#965 Runtime service implementation
  runtime/runtime.go
  runtime/service/service.go
Labels: enhancement

#979 [WIP] Tunnel encryption
  tunnel/crypto.go
  tunnel/crypto_test.go
  tunnel/default.go
  tunnel/listener.go
  tunnel/session.go
Labels: Network, WIP
