Repository micro/go-micro, pull requests merged in 2020-02, with the labels that each got.

#1167 pass micro errors from grpc server to grpc client
  client/grpc/error.go
  client/grpc/grpc_test.go
  errors/errors.go
  errors/errors.pb.go
  errors/errors.proto
  server/grpc/grpc.go
  server/grpc/grpc_test.go
Labels: enhancement

#1161 [WIP] logger first
  logger/field.go
  logger/level.go
  logger/logger.go
  logger/options.go
Labels: Do not merge, WIP

#1186 [WIP] broker/eats: broker disconnect fix
  broker/default.go
  broker/nats/nats.go
Labels: Do not merge, WIP

#1213 fixes for safe conversation and avoid panics
  api/handler/broker/broker.go
  auth/jwt/jwt.go
  client/grpc/grpc.go
  client/rpc_client.go
  codec/codec.go
  codec/proto/proto.go
  codec/protorpc/protorpc.go
  server/grpc/codec.go
  server/grpc/context.go
  server/grpc/grpc.go
  server/grpc/options.go
Labels: broker, bug, enhancement
